# Generated by Django 4.1.7 on 2023-03-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.product')),
                ('image', models.ImageField(blank=True, upload_to='dish/%Y/%m/%d/')),
                ('preparation_time', models.CharField(max_length=30)),
                ('serves', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('P', 'Principal'), ('E', 'Execultivo')], max_length=1)),
            ],
            bases=('core.product',),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.product')),
                ('image', models.ImageField(blank=True, upload_to='drink/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('D', 'DESTILADOS'), ('A', 'ALCOOLICAS'), ('S', 'SEM ALCOOL'), ('C', 'CERVEJAS')], max_length=1)),
                ('quantidade', models.CharField(max_length=100)),
            ],
            bases=('core.product',),
        ),
    ]
